<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>22MasterCard</name>
   <tag></tag>
   <elementGuidId>bd3ec987-ffe8-4c0a-a980-8562ff63dafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-method-MASTER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-method-MASTER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61c276c5-a1d1-449c-8957-95b6b342c3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fIIVfa kpnFiI bigtix-card</value>
      <webElementGuid>fa2d6580-27f4-4440-807f-c351591ddf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-method-MASTER</value>
      <webElementGuid>9660851c-f113-49a1-8073-a397d0e0f1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cardkey</name>
      <type>Main</type>
      <value>MASTER</value>
      <webElementGuid>0df25812-06f0-4204-8760-bdff5647f8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>card-online-payment</value>
      <webElementGuid>b8161297-e007-4211-abb5-6fd109bf3bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f798bd7-33d8-465f-a5fc-fb7306c0b3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mastercard</value>
      <webElementGuid>db5c5a96-3625-4a97-89d6-bf1d0fac8c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method-MASTER&quot;)</value>
      <webElementGuid>f573b86e-5adc-41d8-8fa9-92fc2aa8d1dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='payment-method-MASTER']</value>
      <webElementGuid>95cd51b2-0f78-46cd-bbba-f3d703eb5a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/div/main/div[2]/div[3]/div[2]/div[3]/div</value>
      <webElementGuid>b9f4200f-8efc-4fba-9d8d-37279f5924f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visa'])[1]/following::div[2]</value>
      <webElementGuid>e5bee3c1-5064-454e-8e4a-c763b045d768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE'])[1]/following::div[9]</value>
      <webElementGuid>152cf2aa-e720-47ea-87f5-f2af6f2aec16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JCB'])[1]/preceding::div[7]</value>
      <webElementGuid>a5b80f5f-0190-410b-9a2d-b7a7fb914ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div</value>
      <webElementGuid>baa2d4a3-541b-467b-b358-ada939546d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'payment-method-MASTER' and (text() = 'Mastercard' or . = 'Mastercard')]</value>
      <webElementGuid>66b582b3-3623-4f47-98c4-1862ce7d5a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
