<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>23CardNumber</name>
   <tag></tag>
   <elementGuidId>11455a0b-0fe6-4e1f-aaf5-3e2d648f418a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditcard_cardNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creditcard_cardNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec2d7019-06b1-49d2-9325-0ab2f30f5c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>400e188d-8ad9-4e5a-8d6a-3cf6969ecaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>maskInput</value>
      <webElementGuid>6df657f7-2227-40ca-a9fa-efa22eacb702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1111 1111 1111 1111</value>
      <webElementGuid>2e6b9d97-348e-48e9-95ff-ad0bc153a799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234 5678 9101 1121</value>
      <webElementGuid>310a8e42-1e85-486b-afc8-528da90c7c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-cardNumber</value>
      <webElementGuid>e107d4e0-33a8-44ba-a2df-298fa21b7c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditcard_cardNumber</value>
      <webElementGuid>203ce6ea-e0a0-4387-bdfe-e13b84536a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-iktFzd gsoyDT focus-visible</value>
      <webElementGuid>901fbb58-40b0-417d-9f20-d73fdd741313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>e7641aeb-184e-44ef-b0f3-87ee0b006d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditcard_cardNumber&quot;)</value>
      <webElementGuid>6aa9d6a1-6f13-4091-bb05-95afd6544f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditcard_cardNumber']</value>
      <webElementGuid>0705163c-52ea-4ec1-979b-3f043789fb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='creditcard']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>b1322887-ed81-4ebe-8be2-5915459e2a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/div/div/input</value>
      <webElementGuid>641aa79f-bdda-4ac0-a03d-b68f4f554340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'maskInput' and @placeholder = '1234 5678 9101 1121' and @id = 'creditcard_cardNumber']</value>
      <webElementGuid>a2f05976-3ec8-4ccd-a0a5-6194740da9a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
