<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>24CardHolderName</name>
   <tag></tag>
   <elementGuidId>fd1055ec-6795-4d70-9dd7-dbe0a2b2b091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditcard_cardHolderName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creditcard_cardHolderName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c0d2767-3f2c-4834-ad16-219b857e5a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72dfd456-a257-4766-b20f-1cf66aba7e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1789922-d79b-4834-a075-19abcc1b8f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Doe</value>
      <webElementGuid>1895dab7-8e61-45a6-b938-fb107f3309f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-cardHolderName</value>
      <webElementGuid>c6dd0ab5-5e17-48d4-b526-25d25b71654f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditcard_cardHolderName</value>
      <webElementGuid>89cfb800-4157-48ce-b3e1-3c45e3defc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-bYEvPH hmCNNt focus-visible</value>
      <webElementGuid>cdbe82dd-ea7c-4269-be25-2593a0209b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditcard_cardHolderName&quot;)</value>
      <webElementGuid>7d7ea6b2-0ddf-4e26-a0cb-128dfb405e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditcard_cardHolderName']</value>
      <webElementGuid>4831c348-c15d-49ab-b0b2-2b7cd9d84f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='creditcard']/div[3]/div[2]/div/div/input</value>
      <webElementGuid>86c526c7-2412-4dcf-90e6-e744e9c1f73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>6beba800-c1fb-4681-8768-9f82d31d44b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'John Doe' and @id = 'creditcard_cardHolderName']</value>
      <webElementGuid>1337b8af-299f-4921-bd49-68b3cdf1cae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
