<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>25EXMonth</name>
   <tag></tag>
   <elementGuidId>efd00580-0c1f-492d-8f2f-1407033502d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditcard_expiryMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creditcard_expiryMonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c645a64c-da28-414e-ab65-5d91a4c2d6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>maskInput</value>
      <webElementGuid>17b9adf6-2897-4a3d-807e-528ba0b66c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>0de67e3e-4058-498c-bb80-3cfd23994787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>58b0a13a-018f-4184-9361-8b568734ef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-expiryMonth</value>
      <webElementGuid>35c2fdb0-abf3-488d-9f3d-dfbbd112a6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditcard_expiryMonth</value>
      <webElementGuid>3c761060-0a7c-4b24-b095-c3b112cce713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-iktFzd gsoyDT focus-visible</value>
      <webElementGuid>c92e4e0b-2641-4b37-bc55-5dca944f6679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2c162c3a-1b32-4811-960c-86bd8e2309a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditcard_expiryMonth&quot;)</value>
      <webElementGuid>4dbcc532-3238-420a-88be-3986c29daabe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditcard_expiryMonth']</value>
      <webElementGuid>767cac5f-4589-4e0f-9c04-cef0a5270ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='creditcard']/div[4]/div/div/div/span/div/div[2]/div/div/input</value>
      <webElementGuid>1732404b-9738-4604-9d6d-74d75f3a50fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span/div/div[2]/div/div/input</value>
      <webElementGuid>6458c3a5-2e6f-4000-be1e-84760b0d336c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'maskInput' and @placeholder = '12' and @id = 'creditcard_expiryMonth']</value>
      <webElementGuid>5ab1fd58-f4ae-475e-bc65-d1b741747511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
