<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>25EXYear</name>
   <tag></tag>
   <elementGuidId>e5c81cd7-0deb-47c4-b8bf-0fd3300e185f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditcard_expiryYear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creditcard_expiryYear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>558d411d-de41-4fd6-8301-0ea66ad47956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>547ae296-eda4-4a4e-91f5-1bcf01cbffc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>maskInput</value>
      <webElementGuid>aab0403b-e7b3-4ef8-8365-a9f2d6d43b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>90335362-c189-4234-9422-f7b7c515f70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>9d1e1fa7-4b9d-4154-893d-c296b5a5ae7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-expiryYear</value>
      <webElementGuid>af27ad73-f5bd-496f-8251-9848112f0cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditcard_expiryYear</value>
      <webElementGuid>1258572d-3a07-4c0f-bbd2-171f876780d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-iktFzd gsoyDT focus-visible</value>
      <webElementGuid>6c3da446-1ecf-4f97-b82f-3cb107d398c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>62d8898a-a440-4b1b-9b34-e0b013b59e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditcard_expiryYear&quot;)</value>
      <webElementGuid>23dbd6b7-c6e0-4d76-9e2d-6276d07aff99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditcard_expiryYear']</value>
      <webElementGuid>cf2db1e7-b893-4f65-955e-ac1c2ebed032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='creditcard']/div[4]/div/div/div/span/div[2]/div[2]/div/div/input</value>
      <webElementGuid>f80ffa41-afe5-41f4-8721-ece5ac88f6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span/div[2]/div[2]/div/div/input</value>
      <webElementGuid>7c621310-81f9-4684-adc6-d4e19a9a6551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'maskInput' and @placeholder = '22' and @id = 'creditcard_expiryYear']</value>
      <webElementGuid>f0a69ac9-e22a-4cf2-a44c-32cf738eeb47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
