<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>26CVV</name>
   <tag></tag>
   <elementGuidId>cbdd68e4-e6da-410a-bf8e-ec6d381df017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditcard_cvv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creditcard_cvv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19ffbfb7-3814-4e14-8efc-bb9fb38489a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>31872eae-83e3-4e28-b59e-ab50ff2fc6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>maskInput</value>
      <webElementGuid>59517deb-ebc5-4db5-808c-31366ddaa4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>111</value>
      <webElementGuid>9fc0d1c2-ba6d-424b-b7fa-66add5e21f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123</value>
      <webElementGuid>eff61bf4-a68f-4c74-9c44-104c50ef4418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-cvv</value>
      <webElementGuid>24415356-7977-4a5c-a4d1-eb0e8df75adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditcard_cvv</value>
      <webElementGuid>d66bfd38-3168-4628-b188-f447251c487a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-iktFzd gsoyDT focus-visible</value>
      <webElementGuid>77c12cdc-14af-4311-be72-43c36208bebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3796d435-b9c5-4d7a-ae9a-a504046d3412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditcard_cvv&quot;)</value>
      <webElementGuid>0614ede6-dae0-4dfe-a8bd-586ff1048d63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditcard_cvv']</value>
      <webElementGuid>8357dc29-a934-457e-a21d-2a84c6a0ecd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='creditcard']/div[4]/div/div/div/span/div[3]/div[2]/div/div/input</value>
      <webElementGuid>43196d6c-807b-4d31-b44f-60f252f07087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[3]/div[2]/div/div/input</value>
      <webElementGuid>1b58c4af-fe80-4c1d-a076-c5541a9f0248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'maskInput' and @placeholder = '123' and @id = 'creditcard_cvv']</value>
      <webElementGuid>66ed6186-205f-4c6f-a8ba-05517ebc61e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
