<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>27buttonCONFIRM</name>
   <tag></tag>
   <elementGuidId>a40b6218-0f2f-49ed-9f37-74b63f4e3a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#creditcard > button.ant-btn.ant-btn-primary.sc-gHftXq.fIFJIG.bmspos-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57a07908-bf75-43a3-8359-9f747cc14971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typo</name>
      <type>Main</type>
      <value>ButtonS</value>
      <webElementGuid>0a7e5f55-3b9d-4bc2-9dff-b794361c1d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6e20fbc5-3b9c-45e0-9308-67d14051a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary sc-gHftXq fIFJIG bmspos-button</value>
      <webElementGuid>d8b1dca1-0f20-4990-8fbd-7a33362470ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONFIRM</value>
      <webElementGuid>8e4cc60d-35c2-4752-bcf1-554fb418e57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditcard&quot;)/button[@class=&quot;ant-btn ant-btn-primary sc-gHftXq fIFJIG bmspos-button&quot;]</value>
      <webElementGuid>575d6bf5-07f5-4d4e-a3a4-24e3e5cf6009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>667df488-ed09-4a73-85be-47b18adbf117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='creditcard']/button</value>
      <webElementGuid>d4466509-f90b-4a51-bcdb-13e845bccfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVV'])[1]/following::button[1]</value>
      <webElementGuid>01cbd335-c486-47a7-9954-39db0940727f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Expiry'])[1]/following::button[1]</value>
      <webElementGuid>ca3b7da9-de9a-4756-b72c-8923a0257f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JCB'])[1]/preceding::button[1]</value>
      <webElementGuid>92780efd-4191-4bab-9d0b-a1f2423bc936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/form/button</value>
      <webElementGuid>dce22161-e141-4383-b7bb-f81abd842b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'CONFIRM' or . = 'CONFIRM')]</value>
      <webElementGuid>931e96e9-f7d6-45b3-a3bf-f6b7b86cac54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
