<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>29button_BACK TO HOME</name>
   <tag></tag>
   <elementGuidId>764af781-3a24-4627-85f0-e64540096a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-secondary.sc-gHftXq.bbBLIB.bmspos-button.sc-bIMZcE.bmHBqe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31c92f05-ad74-4773-a2cc-15eae1759070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typo</name>
      <type>Main</type>
      <value>ButtonS</value>
      <webElementGuid>8398d4a0-b493-4ad7-a929-690ca1785df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab89f7e3-491d-407f-b4c3-ae2ef881992e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-secondary sc-gHftXq bbBLIB bmspos-button sc-bIMZcE bmHBqe</value>
      <webElementGuid>aa75e576-1fe4-4772-aa39-770df905acc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BACK TO HOME</value>
      <webElementGuid>771ed982-5d8e-4e89-8cdf-510c194abb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout sc-gsTCUz eqTDWM&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;sc-ksSWxP gSHsI&quot;]/button[@class=&quot;ant-btn ant-btn-secondary sc-gHftXq bbBLIB bmspos-button sc-bIMZcE bmHBqe&quot;]</value>
      <webElementGuid>c259f882-6273-487f-b1ea-43abcff92c07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>7068073d-a114-4464-950d-18bb409d4236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div[3]/button</value>
      <webElementGuid>96eb51b8-6465-49e4-869c-9e9fcf70adcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ivan@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>bf5b885a-8113-4443-819b-3600ef5af288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>1ce381dc-648e-431b-86be-8f9c90d9b3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRINT TICKET'])[1]/preceding::button[1]</value>
      <webElementGuid>09cf0787-42dc-4190-94c2-b9a16358de43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2e0968dc-c6bb-482f-9afc-47f8c9244c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'BACK TO HOME' or . = 'BACK TO HOME')]</value>
      <webElementGuid>1ea7b0d6-8a01-49fa-aefe-d6795ff96eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
