<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>21_select_Mr.Mrs.Ms</name>
   <tag></tag>
   <elementGuidId>83fccde5-104e-4f27-8049-3b5143a595fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.r-30o5oe.r-1niwhzg.r-1yadl64.r-1p0dtai.r-t1w4ow.r-ubezar.r-majxgm.r-1pi2tsx.r-1r74h94.r-135wba7.r-crgep1.r-orgf3d.r-1ny4l3l.r-10paoce.r-u8s1d.r-3mc0re.r-ipm5af.r-34rx7k.r-417010</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adultForm0']/div/div/div[2]/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>01ddf179-6c41-442c-bc30-39bb286fcb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r-30o5oe r-1niwhzg r-1yadl64 r-1p0dtai r-t1w4ow r-ubezar r-majxgm r-1pi2tsx r-1r74h94 r-135wba7 r-crgep1 r-orgf3d r-1ny4l3l r-10paoce r-u8s1d r-3mc0re r-ipm5af r-34rx7k r-417010</value>
      <webElementGuid>e854371f-c469-4f80-986b-e6194db76eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mr.Mrs.Ms.</value>
      <webElementGuid>041f4b4d-cb75-412c-b0fd-c5776a646696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adultForm0&quot;)/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-bztko3&quot;]/div[@class=&quot;css-1dbjc4n r-1ihkh82 r-bztko3&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-eu3ka r-1wtj0ep r-1ny4l3l r-10paoce r-edyy15&quot;]/select[@class=&quot;r-30o5oe r-1niwhzg r-1yadl64 r-1p0dtai r-t1w4ow r-ubezar r-majxgm r-1pi2tsx r-1r74h94 r-135wba7 r-crgep1 r-orgf3d r-1ny4l3l r-10paoce r-u8s1d r-3mc0re r-ipm5af r-34rx7k r-417010&quot;]</value>
      <webElementGuid>5bc4f084-ce36-405e-bff2-a139745a0440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adultForm0']/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>2b1d4f92-ba86-4ea4-93f6-eb2d1d6b4fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>a6443fd7-07f6-46f0-b044-d1e237b1493e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr.'])[2]/preceding::select[1]</value>
      <webElementGuid>9580713c-21bb-4eeb-bbc7-e6975254f7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>5f2aed27-a820-4c14-993d-270e2a210768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Mr.Mrs.Ms.' or . = 'Mr.Mrs.Ms.')]</value>
      <webElementGuid>89787498-5a3d-4adb-873d-bef2d5efa5ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
