<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15Payment_Visa</name>
   <tag></tag>
   <elementGuidId>919d43b5-e6cf-4eeb-80dc-d7daf70c43fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-fznNTe.iTnsYz.bigtix-card.sc-fzpdyU.fYobAL.bigtix-payment-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bigtix-booking-layout-scroll-id']/div/div[2]/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a83993f3-0304-4791-a08d-41672df1da88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fznNTe iTnsYz bigtix-card sc-fzpdyU fYobAL bigtix-payment-method</value>
      <webElementGuid>aba8ea7b-ceb3-4dc6-9993-ecea691677a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-payment-method</name>
      <type>Main</type>
      <value>VISA</value>
      <webElementGuid>c9e77728-7b48-43fc-8d15-d377f51b47cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>bigtix-test-payment-method</value>
      <webElementGuid>342ad7fb-8540-4b66-aaba-c403223a43d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>ea2187f0-af32-4aaa-9ebc-6683a79e93e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7d5ee40-efde-4032-b5a1-b769c8371542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visa</value>
      <webElementGuid>42e56992-d9ad-4ea7-b947-189e06efcc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-layout-scroll-id&quot;)/div[@class=&quot;bigtix-booking-layout-body-content-container&quot;]/div[@class=&quot;bigtix-booking-layout-body-content-main bigtix-booking-layout-body-fullheight&quot;]/div[@class=&quot;sc-fznJRM bTIjTR&quot;]/div[@class=&quot;Payment__PaymentFormContainer-sc-1macogx-0 qzaOx&quot;]/div[@class=&quot;rc-collapse sc-fzoOEf buUIAw sc-fzppip dnjuJf Accordion__StyledPaymentAccordion-ujfzfr-0 enjxHh bigtix-accordion&quot;]/div[@class=&quot;rc-collapse-item&quot;]/div[@class=&quot;rc-collapse-header&quot;]/div[@class=&quot;sc-fznNTe iTnsYz bigtix-card sc-fzpdyU fYobAL bigtix-payment-method&quot;]</value>
      <webElementGuid>356602e7-f8a6-472c-bc4c-2a6cc698cbaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-layout-scroll-id']/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>0261b03e-9c19-4a9d-a33f-9bdc14ccea96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[2]/following::div[10]</value>
      <webElementGuid>8f65a622-18b3-4342-8d61-54fb6f1bcff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expires in 08:10'])[1]/following::div[18]</value>
      <webElementGuid>b04b06a2-d9c1-41cd-82aa-ea3fc7c3b8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mastercard'])[1]/preceding::div[7]</value>
      <webElementGuid>dd5fad28-88f1-4c75-a3d7-0a9188a68d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>ccdf0bf3-ddfa-4266-8a15-54beb36e3b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Visa' or . = 'Visa')]</value>
      <webElementGuid>1d04b87f-7304-41d1-a874-c3c28aa95cfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
