<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>16Cardholder_Name</name>
   <tag></tag>
   <elementGuidId>e09c222b-c85d-44ec-b937-7145cf5ba841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cardholderName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cardholderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b818d333-3daf-4318-aac7-bb1cc345f4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzoXWK hNbLid bigtix-creditcard-name bigtix-input-basic focus-visible</value>
      <webElementGuid>a34004b7-1e3d-47fd-a299-feb7b665ce81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>766ffffb-a61e-41cf-80ae-cbf4a554a36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardholderName</value>
      <webElementGuid>477c9a0d-9530-4137-be30-53175bf2a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-name</value>
      <webElementGuid>0cd2ecb9-4c7c-4a16-b71c-fbf4a555d357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-label--cardholderName</value>
      <webElementGuid>a7bdf6ad-3e94-4ef5-8134-b2addff6a2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-message--cardholderName</value>
      <webElementGuid>1431eeed-ab17-4cca-bcb7-03a9b0a5c9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8bdb5292-3c93-4932-a616-a241687d7115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--creditcardform-cardname</value>
      <webElementGuid>71015d30-9a4c-4e5a-8a68-561575269b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-formitem__bigtix-checkout-payment-form-field--cardholderName&quot;)/input[@class=&quot;sc-fzoXWK hNbLid bigtix-creditcard-name bigtix-input-basic focus-visible&quot;]</value>
      <webElementGuid>05436bf1-e245-43f6-8d97-a45f0847f6ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cardholderName']</value>
      <webElementGuid>3c536617-3d40-49b5-a19b-331e85093d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-formitem__bigtix-checkout-payment-form-field--cardholderName']/input</value>
      <webElementGuid>5c51b3c3-6d1b-4570-a691-670dfc98f9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>758eb9fc-3d61-4614-ba16-8cfdf82412e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cardholderName']</value>
      <webElementGuid>8637c6fa-7cd8-48ac-a286-069e3a206e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
