<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18Ex_Month</name>
   <tag></tag>
   <elementGuidId>aeb3f2b1-eec0-4416-95e5-95b48db5d37c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cc-exp-month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cc-exp-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ed13293-9cac-43ff-848a-537f40a07fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzoXWK hNbLid bigtix__month bigtix-input-number bigtix-input-basic focus-visible</value>
      <webElementGuid>98027227-0772-42fb-96be-17843183c7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e566188a-5900-44ac-9ad3-a5771b9dba25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc-exp-month</value>
      <webElementGuid>4e3e2881-12fc-4bf8-bc22-f415a689b29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>53894201-a8cf-4d7f-86df-bd1b1b2dc24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp-month</value>
      <webElementGuid>9e6b3578-622c-4631-80fa-1f2b883118ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>07ad2f25-2dcb-40e4-9d29-617ce48bfe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>59993b63-79ae-441e-b8aa-753a09f25ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-label--expiry</value>
      <webElementGuid>3ab2ccbf-c9f8-45e5-814a-0ecace65aec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-message--expiry</value>
      <webElementGuid>cdfe271e-8525-4e37-bcdc-dab352c0acc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4dd1776d-246a-4e83-ac48-f8f08603300a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-formitem__bigtix-checkout-payment-form-field--expiry&quot;)/div[@class=&quot;sc-fzqKVi gHakSm&quot;]/input[@class=&quot;sc-fzoXWK hNbLid bigtix__month bigtix-input-number bigtix-input-basic focus-visible&quot;]</value>
      <webElementGuid>49a2ea34-aeb4-4df9-a1c6-268a9d9607f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cc-exp-month']</value>
      <webElementGuid>b4c86c5a-9993-4634-a7bd-69348471371c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-formitem__bigtix-checkout-payment-form-field--expiry']/div/input</value>
      <webElementGuid>1e99ec5f-920a-4fbd-9201-365749152500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>3e09a8e3-01a0-4e9d-8bf6-4e9da25e6159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'cc-exp-month' and @placeholder = 'MM']</value>
      <webElementGuid>1c635ab2-29f9-469b-b4d4-e74a66c764d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
