<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>19Ex_Year</name>
   <tag></tag>
   <elementGuidId>17ff350e-4b37-4552-b73d-bf31265bc8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cc-exp-year&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cc-exp-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aadef495-a126-4536-af26-514289b2a03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzoXWK hNbLid bigtix__year bigtix-input-number bigtix-input-basic focus-visible</value>
      <webElementGuid>e26a1466-ae02-4b58-b9e2-03221d10c047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e0a356d7-1f4e-44b0-8dad-ea39b7cc4a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc-exp-year</value>
      <webElementGuid>1fbd8e49-16af-47cd-b618-7082c64afded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>85522cb7-1a90-42df-836a-9f794ae7a09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp-year</value>
      <webElementGuid>0da8c0a7-2270-47b5-a721-a232a6e46840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YY</value>
      <webElementGuid>889e7176-9080-46c8-bf54-809fa5d9abf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>41479fe3-f656-40a5-96e1-5e1fd97651a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-label--expiry</value>
      <webElementGuid>321ebf13-24b7-4a73-ab5e-019487ba2332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-message--expiry</value>
      <webElementGuid>ff4a5ddb-a9c8-41c9-9082-ecf739f5820c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>589cb0c8-0e92-439f-bf85-573ad7561480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-formitem__bigtix-checkout-payment-form-field--expiry&quot;)/div[@class=&quot;sc-fzqKVi gHakSm&quot;]/input[@class=&quot;sc-fzoXWK hNbLid bigtix__year bigtix-input-number bigtix-input-basic focus-visible&quot;]</value>
      <webElementGuid>1db3a5be-d09c-418f-97ab-ed7c26750cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cc-exp-year']</value>
      <webElementGuid>439d2093-0bde-4c07-8b05-eed5ddea6518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-formitem__bigtix-checkout-payment-form-field--expiry']/div/input[2]</value>
      <webElementGuid>d78e905f-3bd6-4d95-bb39-ada390365f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>2cfe7556-5564-4ecd-877f-820decc31a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'cc-exp-year' and @placeholder = 'YY']</value>
      <webElementGuid>4d0b6645-1df0-4a7e-8865-32e187940325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
