<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>20CVV</name>
   <tag></tag>
   <elementGuidId>7d73abc0-31a5-4a4c-9b11-8ad8b2f9a7b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cvn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cvn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a720d9a5-03b9-4e88-92e4-b7fb54c92480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzoXWK hNbLid sc-fzoCUK kBjMiw bigtix-creditcard-cvn bigtix-input-number bigtix-input-basic focus-visible</value>
      <webElementGuid>4c007e1a-0284-40c1-bfa3-207da0e8e956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>7f6d9acb-56bf-49a4-8919-a6eb97f8133b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvn</value>
      <webElementGuid>ec1d976f-5411-4ab6-a4b8-aee54a7ac657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>6dfcdfd8-2449-451e-8044-dbd8426de46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>788a727b-e5e0-4db3-b8ee-8ad219be7428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>34a737f7-0e28-45f3-8682-0510fa5c9806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-label--cvn</value>
      <webElementGuid>5bfca5a5-cde1-4767-bc61-eb68ba1c80f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigtix-formitem__bigtix-checkout-payment-form-message--cvn</value>
      <webElementGuid>8a3513c9-ed16-4d89-955e-60519d4b8305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2fa1b1f-c99f-4859-9968-fe9859794b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--creditcardform-cvn</value>
      <webElementGuid>fab3840e-1afa-418a-9064-0783b4d66eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-formitem__bigtix-checkout-payment-form-field--cvn&quot;)/input[@class=&quot;sc-fzoXWK hNbLid sc-fzoCUK kBjMiw bigtix-creditcard-cvn bigtix-input-number bigtix-input-basic focus-visible&quot;]</value>
      <webElementGuid>1bbe7bc0-a866-417b-ba8c-363adfd0bd75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cvn']</value>
      <webElementGuid>b2e1759e-7a1e-42ca-98a8-88160567434d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-formitem__bigtix-checkout-payment-form-field--cvn']/input</value>
      <webElementGuid>575bedbb-bcc2-4b7b-a27e-6ab3ff2851e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>76a81d6d-c347-47e1-a3c6-97ff4b637bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'cvn']</value>
      <webElementGuid>09748263-c935-4b45-8b05-75302c08ac44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
