<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>21Pay_Button</name>
   <tag></tag>
   <elementGuidId>5a4e0fc2-4a78-4da8-accd-1b469ad91b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigtix-booking-next-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bigtix-booking-next-page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5877fbf-2118-4029-b232-b5e997ef4b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0cdc141-24f5-4a6f-a328-0eb63cfafa6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqARJ ebsQAa bigtix-button bigtix-button--primary bigtix-booking-pagenav-next</value>
      <webElementGuid>0b976501-352e-4a33-b5ba-47a7c67dca7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigtix-booking-next-page</value>
      <webElementGuid>6dafee72-cca8-4250-8146-d1e691a0d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--pagenav-next</value>
      <webElementGuid>83a4a197-e341-4ae0-b829-a5a468eb0f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay S$20.00</value>
      <webElementGuid>31cd4d85-32c3-4008-a408-d5684f0ed348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-affixed-container&quot;)/div[@class=&quot;sc-fzqMAW jNStJz bigtix-booking-pagenav&quot;]/div[@class=&quot;bigtix-booking-pagenav-buttons&quot;]/div[@class=&quot;bigtix-booking-pagenav-next-container&quot;]/button[@id=&quot;bigtix-booking-next-page&quot;]</value>
      <webElementGuid>77774951-c2ee-4581-a2f6-db0f722f5f1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bigtix-booking-next-page']</value>
      <webElementGuid>96eef1bb-c13e-43f9-9b1b-ef6891607e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-affixed-container']/div/div[2]/div/button</value>
      <webElementGuid>a2f6c0ce-b921-4e28-84af-a5314ea1f9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S$1.66'])[1]/following::button[1]</value>
      <webElementGuid>b20dbea1-236a-4f4c-94f2-7b2be01a608f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SG GST'])[1]/following::button[1]</value>
      <webElementGuid>0343666c-bfcb-4a6a-bf46-4ed588da730e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Summary'])[1]/preceding::button[1]</value>
      <webElementGuid>fa97b950-c5fb-4e27-b41c-4edbc118104a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>fbf3bf4d-57ef-4947-9c34-fb49a894de27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'bigtix-booking-next-page' and (text() = 'Pay S$20.00' or . = 'Pay S$20.00')]</value>
      <webElementGuid>7acb80b5-4610-4da9-ac2c-d30589b9440c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
