<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>22_Back_To_Home</name>
   <tag></tag>
   <elementGuidId>c6ca7db1-d5a8-4d16-a76d-e865bbcafc2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-fznJRM.ctfYKR.bigtix-button.bigtix-button--primary.bigtix-booking-message-return</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e336810-1ffe-4fb1-8710-b3987709945b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>567c1091-b75d-483e-9229-6afa12db0a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fznJRM ctfYKR bigtix-button bigtix-button--primary bigtix-booking-message-return</value>
      <webElementGuid>57e42a56-2775-4afc-90fc-eb852f93f2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back To Home</value>
      <webElementGuid>e8bc29ae-4338-4aec-9345-d9c80350a707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-layout-scroll-id&quot;)/div[@class=&quot;bigtix-booking-layout-body-content-container&quot;]/div[@class=&quot;bigtix-booking-layout-body-content-main bigtix-booking-layout-body-fullheight&quot;]/div[@class=&quot;sc-fzqNqU eHQjXl bigtix-booking-message Success__StyledMessage-p2m4wh-0 Miytl&quot;]/div[@class=&quot;bigtix-booking-message-buttonsContainer&quot;]/button[@class=&quot;sc-fznJRM ctfYKR bigtix-button bigtix-button--primary bigtix-booking-message-return&quot;]</value>
      <webElementGuid>54dfd913-bee6-444b-bcbc-2a93081a396d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>ceb7b7f7-1f67-4ea4-aaa6-b6422bd8bfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-layout-scroll-id']/div/div/div/div[3]/button</value>
      <webElementGuid>6f144989-dad6-42e3-9e16-e3098d40b14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Notice'])[1]/preceding::button[1]</value>
      <webElementGuid>79d3760b-f127-4464-ade2-703c1d884f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2bd66e81-6924-4e4a-ab7d-3a3e092aaead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Back To Home' or . = 'Back To Home')]</value>
      <webElementGuid>24848f0c-c2c8-4afd-a0a5-bba8b8c623d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
