<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>T1</name>
   <tag></tag>
   <elementGuidId>27ff5049-c0e2-42d9-97e6-6cdc4ce7c989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bigtix-booking-layout-scroll-id']/div/div/div/div/div/div/div/div/div[3]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-fzqARJ.jBMXyF.bigtix-button.bigtix-button--text.Remove__StyledRemove-a4vyt2-0.hpLpiN.bigtix-checkout-cart-breakdown-detailed-product-product-remove > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5963864f-8306-4151-8170-cf5e54a899ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>9e348403-bf8b-40c8-b704-e5540ecc049c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-layout-scroll-id&quot;)/div[@class=&quot;bigtix-booking-layout-body-content-container&quot;]/div[@class=&quot;bigtix-booking-layout-body-content-main bigtix-booking-layout-body-fullheight&quot;]/div[@class=&quot;ShoppingCart__PageContainer-hcqnl9-0 dsBriG&quot;]/div[@class=&quot;ShoppingCart__PageContentContainer-hcqnl9-1 hOZJDe&quot;]/div[@class=&quot;ShoppingCart__StyledContainer-hcqnl9-4 jqVjLa&quot;]/div[@class=&quot;sc-fznJRM ShoppingCart__StyledCartContainer-hcqnl9-5 eKifwP&quot;]/div[@class=&quot;Detailed__StyledContainer-thegxr-0 fsIhPd bigtix-checkout-cart-breakdown-detailed&quot;]/div[@class=&quot;Product__StyledProduct-sc-145bt0y-0 iBFhLd bigtix-checkout-cart-breakdown-detailed-product-product Detailed__StyledCartBreakdownDetailedProduct-thegxr-1 csFqhL&quot;]/div[@class=&quot;Extra__StyledExtra-sc-6etkt2-0 eA-DtRk bigtix-checkout-cart-breakdown-detailed-product-product-extra&quot;]/button[@class=&quot;sc-fzqARJ jBMXyF bigtix-button bigtix-button--text Remove__StyledRemove-a4vyt2-0 hpLpiN bigtix-checkout-cart-breakdown-detailed-product-product-remove&quot;]/div[1]</value>
      <webElementGuid>ef82431d-e342-42ef-9095-33bbc9e59065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-layout-scroll-id']/div/div/div/div/div/div/div/div/div[3]/button/div</value>
      <webElementGuid>41e57b01-3c89-4d54-b81d-75a66fa8cd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S$20.00'])[2]/following::div[1]</value>
      <webElementGuid>058b9c15-1ef2-4dbb-8b39-a3f53cf7b838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automated Venue'])[1]/following::div[3]</value>
      <webElementGuid>549e1c4a-d681-4acf-9ebe-12b8d39ed90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[1]/preceding::div[1]</value>
      <webElementGuid>665d3de6-330c-4d50-b726-69abd6035ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S$20.00'])[3]/preceding::div[3]</value>
      <webElementGuid>12301078-8838-4e77-95d0-c87baf36fe84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>4bae41a7-fe5b-461c-b250-a69d8a78c7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>e9c0dcb6-06d8-4d10-9fea-68041575f420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>82313dee-d20e-4655-bb47-cf723263c217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
