<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01button_Singapore</name>
   <tag></tag>
   <elementGuidId>0df4779c-c108-49a2-a1e1-c5f9dd4686c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-AxiKw.brzbRx.bigtix-button.bigtix-button--ghost.PillList__StyledRegionsButton-sc-1y335zp-1.dRHnhV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34c1b892-8ee8-4fe9-a2e5-3a3e21b85302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57f8a86a-2a48-4574-8ba7-972030504810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-AxiKw brzbRx bigtix-button bigtix-button--ghost PillList__StyledRegionsButton-sc-1y335zp-1 dRHnhV</value>
      <webElementGuid>7946490a-8dd2-4c0f-83e0-cab654aeb717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>ec655bb1-d3dc-4daa-9d86-ada65926e21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singapore</value>
      <webElementGuid>dd481477-d2e9-4b6f-99b5-2f826217b46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sc-fzpjYC gJohPa bigtix-layout Layout__StyledLayoutTemplate-sc-1ptouf0-0 faaGZf&quot;]/div[@class=&quot;sc-fzokOt hLgJkJ bigtix-layout__body&quot;]/div[@class=&quot;bigtix-layout__main&quot;]/div[@class=&quot;BodyContent__StyledContent-sc-5p1m8x-0 cWiblK bmsportal-layout-body-content&quot;]/div[@class=&quot;bmsportal-layout-body-content-container&quot;]/div[@class=&quot;bmsportal-layout-body-content-main&quot;]/div[@class=&quot;Regions__StyledRegionPage-sc-1fauf0r-0 eDBjLO bmsportal-regions&quot;]/div[@class=&quot;List__StyledList-sc-1m5ybmu-0 NvHcI bmsportal-regions-page-list&quot;]/div[@class=&quot;PillList__StyledRegionsPillList-sc-1y335zp-0 gkqTqx bmsportal-region-pill&quot;]/button[@class=&quot;sc-AxiKw brzbRx bigtix-button bigtix-button--ghost PillList__StyledRegionsButton-sc-1y335zp-1 dRHnhV&quot;]</value>
      <webElementGuid>9a512ba1-ef36-4650-8978-ff99bc48cd6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f79fdd61-3178-4dff-9791-15c27d2a07b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>b40d3736-e548-495e-88f2-67a8bfbeb6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose a location'])[1]/following::button[1]</value>
      <webElementGuid>fdaa09fb-9728-48c3-8889-0e8c5ddc276c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::button[1]</value>
      <webElementGuid>eb39ada2-77e0-4929-87d7-197b14eab624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Happening elsewhere'])[1]/preceding::button[1]</value>
      <webElementGuid>0b784311-6a11-4e46-97bb-2cedf715f30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>befadcc6-f5ce-41cd-8c78-ab338db30351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Singapore' or . = 'Singapore')]</value>
      <webElementGuid>f3d381fd-51a8-44a8-a57a-fb5a37f7ba56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
