<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Find_Elements</name>
   <tag></tag>
   <elementGuidId>9ca6d522-7aff-4d4b-9852-b7e5788e8a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/div[3]/div[3]/div/div/div/div/div[2]/div/div/div[6]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '報紙' or . = '報紙')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiDataGrid-row.MuiDataGrid-row--lastVisible.Mui-hovered > div.MuiDataGrid-cell.MuiDataGrid-cell--textLeft.MuiDataGrid-withBorderColor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7799e678-a878-426d-a77c-85665b71fb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDataGrid-cell MuiDataGrid-cell--textLeft MuiDataGrid-withBorderColor</value>
      <webElementGuid>d28093c1-655f-4278-a068-b1b6a4ccdd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>dd87cfc5-fa9f-457d-b9cc-cf39c3f3ee62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>processTypeNameTchi</value>
      <webElementGuid>a8279a96-723d-41ce-b4ed-b89ac9d9744e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-colindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>944af33b-ed62-47f1-8935-e9ca4746d9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b9fecd8-5606-47e9-b38a-b1ce9459ee10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a67fcf43-156e-4f8f-ac3c-561269613460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99631ea3-1c37-4fc2-b1e4-61d3dfdd68ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>報紙</value>
      <webElementGuid>091c9032-3dd7-415b-ba35-f8f7f0d500da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-p41gj9&quot;]/div[@class=&quot;container-wrapper w-max MuiBox-root css-0&quot;]/div[@class=&quot;settings-page bg-bg-primary&quot;]/div[@class=&quot;MuiBox-root css-swezfe&quot;]/div[@class=&quot;table-vehicle&quot;]/div[@class=&quot;MuiBox-root css-1c8tkrp&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-root--densityStandard MuiDataGrid-withBorderColor css-1v53nau-MuiDataGrid-root&quot;]/div[@class=&quot;MuiDataGrid-main css-204u17-MuiDataGrid-main&quot;]/div[@class=&quot;MuiDataGrid-virtualScroller css-qvtrhg-MuiDataGrid-virtualScroller&quot;]/div[@class=&quot;MuiDataGrid-virtualScrollerContent MuiDataGrid-virtualScrollerContent--overflowed css-1kwdphh-MuiDataGrid-virtualScrollerContent&quot;]/div[@class=&quot;MuiDataGrid-virtualScrollerRenderZone css-s1v7zr-MuiDataGrid-virtualScrollerRenderZone&quot;]/div[@class=&quot;MuiDataGrid-row MuiDataGrid-row--lastVisible Mui-hovered&quot;]/div[@class=&quot;MuiDataGrid-cell MuiDataGrid-cell--textLeft MuiDataGrid-withBorderColor&quot;]</value>
      <webElementGuid>1ec020c8-7259-4975-90ae-4705a601b164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div[3]/div[3]/div/div/div/div/div[2]/div/div/div[6]/div</value>
      <webElementGuid>bcd8e8b0-7225-4578-96a5-5c6e44a7de2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::div[13]</value>
      <webElementGuid>c8dc99a7-e15f-415d-a071-75380a0770cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SC'])[1]/following::div[15]</value>
      <webElementGuid>c4c12587-80a2-48a5-b1f7-c0af5d53574b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='报纸'])[1]/preceding::div[2]</value>
      <webElementGuid>d65ec2f1-3a21-4618-bf3f-3e041b1cc677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div</value>
      <webElementGuid>2cf7eec6-8c8d-44bd-a64d-c4c72f331c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '報紙' or . = '報紙')]</value>
      <webElementGuid>a16c48ff-8eb7-42c4-9eab-0b912442fb11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
