<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NewInput_Remark</name>
   <tag></tag>
   <elementGuidId>fba549a5-fd55-4c43-aa30-848527f204a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remark']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9d74180b-4548-4d4a-bf24-cd21951bb252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b217071e-412c-4a43-9c49-56b62c6ba941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53151b5e-e7fc-4be2-a230-2b8761c2f65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>b2eef807-4278-4dee-a99a-e900d55201e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter remark</value>
      <webElementGuid>d7b32d03-5d0a-4de0-85ab-f19bfdf72399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline MuiInputBase-inputHiddenLabel MuiInputBase-inputAdornedEnd css-mixo3p-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>4d742b01-f560-4bee-aec8-b79cf3aab698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remark&quot;)</value>
      <webElementGuid>70e66feb-7674-4687-bf3d-84a0c661ad52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remark']</value>
      <webElementGuid>86c5dc02-ce3a-456f-bcb7-467317f16bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/textarea</value>
      <webElementGuid>57ede02c-50fd-47fc-864f-46528c331bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remark' and @placeholder = 'Please enter remark']</value>
      <webElementGuid>6eda6ffe-cc13-401b-bd1f-34b1c557f667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
