<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05Result</name>
   <tag></tag>
   <elementGuidId>026db284-a9a8-44ac-bd9a-da6b252a29aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div/div[2]/div/div/div/div[2]/div/b/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-TmcTc.hzAphj.ant-tooltip-open.sc-flMoUE.ciwbCw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>364af62e-3e29-4d86-8a16-4c2216cd2f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-TmcTc hzAphj ant-tooltip-open sc-flMoUE ciwbCw</value>
      <webElementGuid>46a90148-35e7-4ddf-9807-d90f149ec74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Automation Test] 20 Nov 2023 7:38 AM GA Bundle</value>
      <webElementGuid>363b8815-c283-4841-b35f-89090390933b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout&quot;]/section[@class=&quot;ant-layout sc-fubCfw jwTLJn&quot;]/main[@class=&quot;ant-layout-content sc-pFZIQ gbgfMs&quot;]/div[@class=&quot;sc-gKsewC jyCpSH&quot;]/div[@class=&quot;sc-gUUzQN iwVrsu&quot;]/div[@class=&quot;ant-row sc-hJxCPi dCyjUe&quot;]/div[@class=&quot;ant-col&quot;]/div[@class=&quot;sc-jHVexB leHYjK bmspos-prod-card bmspos-no-select&quot;]/div[@class=&quot;sc-jONnTn jIvnOH bmspos-prod-detail&quot;]/div[@class=&quot;sc-hlTvYk bkPOGA&quot;]/b[@class=&quot;sc-eLgOdN jiPHbi bmspos-prod-title&quot;]/span[@class=&quot;sc-TmcTc hzAphj ant-tooltip-open sc-flMoUE ciwbCw&quot;]</value>
      <webElementGuid>21460291-054b-4bcd-9a68-c6bb8d1fa170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div[2]/div/div/div/div[2]/div/b/span</value>
      <webElementGuid>327d516c-498d-4fb7-b39e-e34447f6d8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::span[1]</value>
      <webElementGuid>3ba39f56-eded-4942-b607-a362a63f9200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[1]/following::span[4]</value>
      <webElementGuid>d49d74b9-1b53-427e-b073-2c4107ebb7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/preceding::span[2]</value>
      <webElementGuid>bb535775-1872-4cf0-be51-54b2b4d68fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order cart is empty'])[1]/preceding::span[8]</value>
      <webElementGuid>92d75d1f-9c73-4b1d-b7c6-ce49cb692603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[Automation Test] 20 Nov 2023 7:38 AM GA Bundle']/parent::*</value>
      <webElementGuid>b292976e-1d52-4a6b-8bd9-cdd42af53f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/span</value>
      <webElementGuid>26d9cf12-ff6f-4a61-aa66-37f9d52a7b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '[Automation Test] 20 Nov 2023 7:38 AM GA Bundle' or . = '[Automation Test] 20 Nov 2023 7:38 AM GA Bundle')]</value>
      <webElementGuid>ac4741cc-3213-455b-84e2-6d529e1f6486</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
