<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06Schendule</name>
   <tag></tag>
   <elementGuidId>86865075-5b16-43dd-90e7-bf44767442bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bigtix-sessions-list-v2-session-QXG5-2023-11-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigtix-sessions-list-v2-session-QXG5-2023-11-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48129b01-dd7f-40f0-b1d9-54ef06dcde21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7972f40d-59c8-4bfc-9175-80bd23aa4045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gsxnyZ hOkqqk bigtix-button bigtix-button--ghost sc-gqdxRg ldNDuf bigtix-session bigtix-session--oddcell bigtix-session--available bigtix-session--single-date</value>
      <webElementGuid>b2cff67b-009e-44c3-b2fb-d801dfccb13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-session</name>
      <type>Main</type>
      <value>QXG5</value>
      <webElementGuid>43c3f402-5cb6-4114-aa29-fea18848ff47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>bigtix-test-calendar-session</value>
      <webElementGuid>6e491cf3-ef3a-43ec-89b9-22955b1d2717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigtix-sessions-list-v2-session-QXG5-2023-11-4</value>
      <webElementGuid>fc640389-3f3e-45f3-b185-c9dfb10fc940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7:39 AM</value>
      <webElementGuid>533d1921-1e17-4f13-9172-15e734209b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-sessions-list-v2-session-QXG5-2023-11-4&quot;)</value>
      <webElementGuid>97b37978-b788-4d2b-b1da-e33a771136ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bigtix-sessions-list-v2-session-QXG5-2023-11-4']</value>
      <webElementGuid>a74e4627-fcb6-415c-9b0e-224e4a6a0589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-sessions-list-v2-day-2023-11-4']/div[2]/button</value>
      <webElementGuid>b87ca1dd-2b19-4177-a7ba-a050f6c1f762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[2]/following::button[1]</value>
      <webElementGuid>caca7cc0-1bb5-4c25-9694-0500c38e43cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December 2023'])[1]/following::button[1]</value>
      <webElementGuid>a9351d95-7923-47de-b4ef-2092df672512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/preceding::button[1]</value>
      <webElementGuid>980fb960-e517-4eb9-a5a3-664f19e3755a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selling fast'])[1]/preceding::button[1]</value>
      <webElementGuid>db75e811-0543-4699-a711-4d45094c2286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button</value>
      <webElementGuid>1e40e134-a14e-42a6-b6df-67e0b33ea652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'bigtix-sessions-list-v2-session-QXG5-2023-11-4' and (text() = '7:39 AM' or . = '7:39 AM')]</value>
      <webElementGuid>3908e155-6f54-41bb-a495-e91425b9df00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
