<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07ConfirmSelection</name>
   <tag></tag>
   <elementGuidId>84a4c764-2115-4c1e-bd5d-8abbf8e0c81e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-primary.ant-btn-block.sc-gHftXq.fIFJIG.bmspos-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fd442b4-8e3f-40c4-9cf8-098bfdb95e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typo</name>
      <type>Main</type>
      <value>ButtonS</value>
      <webElementGuid>733b5fe5-871e-4b5d-b54c-e30a90b7901f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6768bc2-172e-448b-a728-22eeaa0f32b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button</value>
      <webElementGuid>4cc91c4b-1403-43d2-b658-83db45ccadef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONFIRM SELECTION</value>
      <webElementGuid>b665d95f-7b1a-401a-be59-aa01828cd3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bmspos--layout-scroll-id&quot;)/div[@class=&quot;sc-fFubgz cSXbnk&quot;]/aside[@class=&quot;ant-layout-sider ant-layout-sider-dark sc-kstrdz JCRiS&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/div[@class=&quot;sc-cBNfnY ljIXsm&quot;]/div[@class=&quot;sc-citwmv kODJIQ bmspos-progress-timeline&quot;]/div[@class=&quot;sc-iBaPrD kgzbzw&quot;]/div[@class=&quot;sc-ljwYwh TvPmz&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button&quot;]</value>
      <webElementGuid>9a2684f8-a795-4ba6-a621-f0fc0437b2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>af81711f-4ec6-464b-8245-4863cab95e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='bmspos--layout-scroll-id']/div/aside/div/div/div/div[2]/div/button</value>
      <webElementGuid>c11739f0-8864-4acc-8587-6e22f377ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery &amp; Tickets'])[1]/following::button[1]</value>
      <webElementGuid>50ffd989-511b-403e-a4b8-6ad74588178d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category &amp; Quantity'])[1]/following::button[1]</value>
      <webElementGuid>d043aba5-4fdf-44ad-b878-363f84add265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>ccc6cf65-75c0-40b7-8643-bd8611392a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/div[2]/div/button</value>
      <webElementGuid>0d43ecab-173d-4e5c-8bb5-338f9a1855a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'CONFIRM SELECTION' or . = 'CONFIRM SELECTION')]</value>
      <webElementGuid>259903c1-bd63-4449-aba4-e329a0ecff78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
