<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12FullName</name>
   <tag></tag>
   <elementGuidId>086b4a24-4148-4c6b-9f18-305de743bb47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patron-mailing-information_fullName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#patron-mailing-information_fullName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>382a77bb-fb7d-4c60-a1c3-f3f78be6bfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34f326d5-5f1b-4ab0-826d-1101f4d7433a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Doe</value>
      <webElementGuid>477adb19-df00-4303-8bcd-68e5e07c3019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-fullName</value>
      <webElementGuid>d8710a6f-3b97-4dff-83d4-9d2a01f58e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patron-mailing-information_fullName</value>
      <webElementGuid>339d4a20-98c6-4176-969f-a652bd5fde76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-bYEvPH hmCNNt focus-visible</value>
      <webElementGuid>f355d2e3-7db1-44fc-b9cc-a14ab6ce9803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patron-mailing-information_fullName&quot;)</value>
      <webElementGuid>6d7be10f-0155-4977-8ed5-beee5c063933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patron-mailing-information_fullName']</value>
      <webElementGuid>03e1dce2-d770-4ea6-b201-ee216f3e00e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patron-mailing-information']/div[5]/div[2]/div/div/input</value>
      <webElementGuid>a2dd261d-3ca0-4f0e-a2fb-4da96484ff60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>64c3d078-e6b5-47fb-b5e0-413c9adc86cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'John Doe' and @id = 'patron-mailing-information_fullName']</value>
      <webElementGuid>6b18d051-9c69-4855-b96c-cf32339a2a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
