<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>14SearchCounty</name>
   <tag></tag>
   <elementGuidId>99f050ac-c79a-4ce5-9549-101b2a198dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='patron-mailing-information']/div[7]/div[2]/div/div/span/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-select-selection-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5586092a-68eb-4386-b01e-8e5374fbd36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>838cde1c-9c6b-4c90-bb37-c8ed73ac4ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Singapore: +65</value>
      <webElementGuid>60b644cc-0b46-47b4-b3bf-619332485d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singapore: +65</value>
      <webElementGuid>07aaba35-dea3-4caa-b76e-2867b34fcddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patron-mailing-information&quot;)/div[@class=&quot;ant-row ant-form-item&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/span[@class=&quot;ant-input-group ant-input-group-compact&quot;]/div[@class=&quot;ant-select sc-jJEJSO bLdkYe ant-select-focused ant-select-single ant-select-allow-clear ant-select-show-arrow ant-select-show-search&quot;]/div[@class=&quot;ant-select-selector&quot;]/span[@class=&quot;ant-select-selection-item&quot;]</value>
      <webElementGuid>993deff5-d855-4826-9ed5-6404c16519f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patron-mailing-information']/div[7]/div[2]/div/div/span/div/div/span[2]</value>
      <webElementGuid>439b9a93-93fe-44f2-8311-86179dd0e38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore: +65'])[1]/following::span[2]</value>
      <webElementGuid>5e9b9bfb-4051-4092-a9a9-2348aeaef13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Number'])[1]/following::span[4]</value>
      <webElementGuid>2aaf6108-00a1-41b1-842d-679ac140c74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Address'])[1]/preceding::span[5]</value>
      <webElementGuid>9a458eff-e40b-4b7c-9407-3bc502fd0c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Same as delivery address'])[1]/preceding::span[7]</value>
      <webElementGuid>995d0cbc-3a50-4f70-9f8d-c7b2180fb743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/span[2]</value>
      <webElementGuid>b246130d-b767-4c7a-93d1-ec0429a7f04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Singapore: +65' and (text() = 'Singapore: +65' or . = 'Singapore: +65')]</value>
      <webElementGuid>314992eb-e192-48ee-af2b-55e5b43c4c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
