<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>16SingaporeNumber</name>
   <tag></tag>
   <elementGuidId>38a8a022-06c5-4f33-9e00-609dd670917c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patron-mailing-information_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#patron-mailing-information_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76d3b781-628d-4962-a46d-d785a675cc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>aad2aca8-5225-4b54-a88b-6838707edad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-phone</value>
      <webElementGuid>097584bb-7b82-4fb3-9e73-d7af55b0e018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patron-mailing-information_phone</value>
      <webElementGuid>192e0b2c-dd91-43ce-8666-8b0ef1c53233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-bYEvPH hmCNNt focus-visible</value>
      <webElementGuid>d4dfe16b-1006-4a09-8b45-eff32f0bf69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patron-mailing-information_phone&quot;)</value>
      <webElementGuid>0b01599c-bb22-4bde-bc30-85605a5fee18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patron-mailing-information_phone']</value>
      <webElementGuid>33944d21-7673-4908-b008-957e75139622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patron-mailing-information']/div[7]/div[2]/div/div/span/input</value>
      <webElementGuid>c3d85a58-b789-4339-9a92-3afa71d86181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>ee9ba2a6-5c58-42cc-bc28-43db453d1c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'patron-mailing-information_phone']</value>
      <webElementGuid>8010c19b-e681-43a5-ba20-e63ba5fe254d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
