<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>17Addreas</name>
   <tag></tag>
   <elementGuidId>7960a1a3-f9c2-4698-b776-8b939d4cbde0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patron-mailing-information_billingAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#patron-mailing-information_billingAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>648571c1-9325-4874-965b-f4b5bd0fee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31142ab8-f77b-4d11-8515-33e9be193d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>380 Jalan Besar</value>
      <webElementGuid>1f6de6dd-c3ff-4f9d-9a11-43fe4eb2c16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-billingAddress</value>
      <webElementGuid>1fb06a13-8836-423d-bcf3-f76103720ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patron-mailing-information_billingAddress</value>
      <webElementGuid>c20b515c-3bb3-4697-8e25-1b4e5671d5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-bYEvPH hmCNNt focus-visible</value>
      <webElementGuid>913ef5da-c5ba-449a-87d7-c9220b50e376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patron-mailing-information_billingAddress&quot;)</value>
      <webElementGuid>1a666c12-05ba-4306-a917-2608677a304d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patron-mailing-information_billingAddress']</value>
      <webElementGuid>ac25d0f8-1c42-4a77-a47a-f9886dfc5483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patron-mailing-information']/div[11]/div[2]/div/div/input</value>
      <webElementGuid>5d1d05c0-3fb5-40f7-aada-f5ad0b0410ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div/input</value>
      <webElementGuid>18e86e88-b9aa-4655-a942-c9389daf4626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = '380 Jalan Besar' and @id = 'patron-mailing-information_billingAddress']</value>
      <webElementGuid>58dd1f78-4d2b-46ea-96f1-bbf5bff50b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
