<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18Country</name>
   <tag></tag>
   <elementGuidId>1a9ebf25-48a0-49e9-8138-9b5df0f35458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patron-mailing-information_billingCountry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#patron-mailing-information_billingCountry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f81b45-d868-4b95-94e3-a759cdc946e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patron-mailing-information_billingCountry</value>
      <webElementGuid>8e215cc8-66dc-4d51-ac14-0799e52ea21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9dac662-0cfc-4aec-a8bb-7beb8cdf4005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>2ff6980e-42df-49b9-a406-ddd09c648e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input focus-visible</value>
      <webElementGuid>8a0b9fbc-1f92-44c8-a71e-766d8e555bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c326ed31-f033-45f4-a49a-95e6a7edca18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3d00d578-aada-4910-b70a-a4953765529c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>patron-mailing-information_billingCountry_list</value>
      <webElementGuid>d178dd4a-ae19-4d78-9051-babbf0e4d88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>6bc06e2c-5e76-42ed-9456-551f5dbbd4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>patron-mailing-information_billingCountry_list</value>
      <webElementGuid>41a2c616-bc7d-472e-9774-c186cc5ae152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>patron-mailing-information_billingCountry_list_0</value>
      <webElementGuid>5d384fdc-9336-445a-bc78-4f1777d1bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95a61687-e369-40e8-ba09-2a1412d700ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patron-mailing-information_billingCountry&quot;)</value>
      <webElementGuid>ec95af08-3958-46c8-89c0-e308a12ec854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patron-mailing-information_billingCountry']</value>
      <webElementGuid>6724d52b-5dd0-4ee2-8360-741ea0eaa04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patron-mailing-information']/div[13]/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>b4edcfd2-4464-4ec5-b4d1-9ffb08441679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>30697c36-3527-4344-998d-273e80920680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'patron-mailing-information_billingCountry' and @type = 'search']</value>
      <webElementGuid>bb656814-ffa1-40e4-8627-863b9ebb64ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
