<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>20PostalCode</name>
   <tag></tag>
   <elementGuidId>956d653e-5866-404a-a33e-160d7a39e9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patron-mailing-information_billingPostalCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#patron-mailing-information_billingPostalCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe5dd523-24e7-4e7e-881c-afb294398f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>854ba5f4-2e77-415c-9ccd-ecf517d36a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>input-billingPostalCode</value>
      <webElementGuid>d03b97e4-f4b5-40f0-8426-9ed8cc0b3128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patron-mailing-information_billingPostalCode</value>
      <webElementGuid>c2a7fe03-452e-4b4c-b9b0-d8ceb40b26d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-bYEvPH hmCNNt focus-visible</value>
      <webElementGuid>1c380502-091d-453f-9e7e-7d70754a3557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patron-mailing-information_billingPostalCode&quot;)</value>
      <webElementGuid>dd248bfc-cadf-4264-a79b-d3a847ce31c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patron-mailing-information_billingPostalCode']</value>
      <webElementGuid>aa23bfae-70a4-4c2a-abe3-0cb78fcfd63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patron-mailing-information']/div[15]/div/div/div/span/div[2]/div[2]/div/div/input</value>
      <webElementGuid>2f24a9ae-389e-415e-afff-68e5a165c07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>c73f2baf-09fa-4178-9cc7-5582871222b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @id = 'patron-mailing-information_billingPostalCode']</value>
      <webElementGuid>d2ddb02a-7a72-472d-884a-28ba4d8d79e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
