<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10Checkout</name>
   <tag></tag>
   <elementGuidId>248c548b-d0af-4edc-a672-89e62980b02e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Checkout' or . = 'Checkout')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='bigtix-booking-next-page'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7cb3387-0960-42ff-8a15-934a202e1bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca4d8062-4df2-4d13-bf9b-aee5a9a650f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqARJ ebsQAa bigtix-button bigtix-button--primary bigtix-booking-pagenav-next</value>
      <webElementGuid>5f2e1fe0-10d9-423c-ac02-8af790e612e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigtix-booking-next-page</value>
      <webElementGuid>3c86e225-5b20-4e77-86e0-396be52ae499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--pagenav-next</value>
      <webElementGuid>67b4245a-f361-4bc3-a5bd-d5b2d3a5b052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>2ad922e4-9838-41ca-8fd5-2add3bc1a081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-affixed-container&quot;)/div[@class=&quot;sc-fzqMAW dqXXeL bigtix-booking-pagenav&quot;]/div[@class=&quot;bigtix-booking-pagenav-buttons&quot;]/div[@class=&quot;bigtix-booking-pagenav-next-container&quot;]/button[@id=&quot;bigtix-booking-next-page&quot;]</value>
      <webElementGuid>944694cb-b18f-40a6-af44-5286136b4fb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='bigtix-booking-next-page'])[2]</value>
      <webElementGuid>a5211e1e-6b80-4c78-b133-d890d3b033d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-affixed-container']/div/div/div/button[2]</value>
      <webElementGuid>dcc37c93-3b77-4abb-ba90-96b21953b71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/following::button[1]</value>
      <webElementGuid>21da33a0-2c05-4490-9e81-bd14040a5576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Notice'])[1]/following::button[2]</value>
      <webElementGuid>b08616ff-9aa2-4ae7-b97b-af53c399affc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>037e08ce-7790-488f-8601-fdb79f85f20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'bigtix-booking-next-page' and (text() = 'Checkout' or . = 'Checkout')]</value>
      <webElementGuid>d6c32462-cc4c-4296-8515-973678384c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
