<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>13Singapore_Phone</name>
   <tag></tag>
   <elementGuidId>d5097378-f7f1-4615-9bed-7fcfd55a9100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19afe6db-707b-45e9-bce4-4b694e9073b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzoXWK hNbLid bigtix-patroninfo-phone__number bigtix-input-number bigtix-input-basic</value>
      <webElementGuid>851ec619-c8cf-4992-a2cd-bd38576b1ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>b7b3e92c-6fca-4cab-b26a-efc03e6fa200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>b5b54840-f535-47d3-8014-ad1433bfa919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a3e3e2b2-1898-4383-835e-b9d58a97e3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>bigtix-formitem__patronInfo-label--phone</value>
      <webElementGuid>d660647c-2497-4d03-9226-eaa78223a636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigtix-formitem__patronInfo-message--phone</value>
      <webElementGuid>2ab01905-3d0e-4ab7-990d-91376f47cf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90a5556a-ae7d-464c-bf73-79a029351c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--patroninfoform-phone</value>
      <webElementGuid>6c1581d3-8a3c-4334-9eda-21bc4f80b070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone number</value>
      <webElementGuid>bb4a9e1a-4f0b-4773-b78e-6be80728a992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-formitem__patronInfo-field--phone&quot;)/div[@class=&quot;sc-fzqLLg eRrdRa bigtix-patroninfo-phone&quot;]/div[@class=&quot;bigtix-patroninfo-phone__group&quot;]/input[@class=&quot;sc-fzoXWK hNbLid bigtix-patroninfo-phone__number bigtix-input-number bigtix-input-basic&quot;]</value>
      <webElementGuid>def19f99-5aa2-4dae-b3b7-3211c74654bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
      <webElementGuid>dd08b41b-171e-460a-81d2-dc02e3f4a046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-formitem__patronInfo-field--phone']/div/div[2]/input</value>
      <webElementGuid>3d1e1139-cd49-4b71-bd69-5265cbf81b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cf42ff03-481c-46e2-85c4-e896bf72584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'phone' and @placeholder = 'Phone number']</value>
      <webElementGuid>0a4d62e0-6cb7-4c85-824c-2490ca0a7b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
