<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>14Confirm_Details</name>
   <tag></tag>
   <elementGuidId>07e1db7b-b2d9-4d01-80fb-b3d8621db9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bigtix-booking-next-page']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigtix-booking-next-page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cd6e67f-6e36-475b-803e-360240421c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3ee06dc-a46e-41ee-9229-de2a2f5b75a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzqARJ ebsQAa bigtix-button bigtix-button--primary bigtix-booking-pagenav-next</value>
      <webElementGuid>fe7004bc-b201-41bf-93f9-d5c0053ef91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigtix-booking-next-page</value>
      <webElementGuid>3f9f930e-720a-4dfb-aa39-a39d7fa8ae06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--pagenav-next</value>
      <webElementGuid>a8337af0-4e36-4efc-9768-dd3292b6f701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm details</value>
      <webElementGuid>0d55240d-a53d-4693-8ba3-064cdd3e1ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-affixed-container&quot;)/div[@class=&quot;sc-fzqMAW jNStJz bigtix-booking-pagenav&quot;]/div[@class=&quot;bigtix-booking-pagenav-buttons&quot;]/div[@class=&quot;bigtix-booking-pagenav-next-container&quot;]/button[@id=&quot;bigtix-booking-next-page&quot;]</value>
      <webElementGuid>0e5254a8-812c-4f6b-8d77-a6ca894244e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bigtix-booking-next-page']</value>
      <webElementGuid>df894f92-f8c5-4e0e-b95d-823b4994af90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-affixed-container']/div/div[2]/div/button</value>
      <webElementGuid>c65dcb4c-2fc6-4213-a177-a57f07f7f883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S$1.66'])[1]/following::button[1]</value>
      <webElementGuid>6b767984-ef77-4ec7-9ce4-d5cd35be34f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SG GST'])[1]/following::button[1]</value>
      <webElementGuid>8f2a9779-d815-400c-bbf2-1704279155db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Summary'])[1]/preceding::button[1]</value>
      <webElementGuid>479ef2b1-f995-4c02-a3df-ec2120eb7984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>e3ae4553-2adf-4680-87ca-f1073a5d51dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'bigtix-booking-next-page' and (text() = 'Confirm details' or . = 'Confirm details')]</value>
      <webElementGuid>977e31e3-3c93-49eb-aa7b-f1442e2c2d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
