<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08AddManual</name>
   <tag></tag>
   <elementGuidId>f45e8e44-cda2-42f7-b641-1d60447dc055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-gsxnyZ.KDPRS.bigtix-button.bigtix-button--primary.bigtix-quantity-stepper__stepper.bigtix-quantity-stepper__plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cdf0491-bf3d-4351-8641-8c6a42e8ba39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98ca3914-2ccc-4084-919e-103c6116700e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gsxnyZ KDPRS bigtix-button bigtix-button--primary bigtix-quantity-stepper__stepper bigtix-quantity-stepper__plus</value>
      <webElementGuid>09d2e56d-aca0-44c9-8d4c-4493791a69a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>bigtix-test-quantity-select-add</value>
      <webElementGuid>9fe8a038-9028-42ee-923a-f95ea98e43c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bmspos--layout-scroll-id&quot;)/div[@class=&quot;sc-fFubgz cSXbnk&quot;]/main[@class=&quot;ant-layout-content sc-bkzZxe fRXSVe&quot;]/div[@class=&quot;sc-eYErCu gKdRlB bmspos-panel-wrapper&quot;]/div[@class=&quot;sc-bHXZN fPVBKk&quot;]/ul[@class=&quot;sc-iOTrKq iCLerG&quot;]/div[@class=&quot;sc-fEcgnn gnGiqn&quot;]/div[@class=&quot;sc-mlOqW flXQvI&quot;]/div[@class=&quot;sc-ctaXAZ jddcAm bmspos-qty-selection-wrapper&quot;]/div[@class=&quot;bmspos-qty-stepper-wrapper&quot;]/div[@class=&quot;sc-eGCarw kmThIt bigtix-quantity-stepper&quot;]/button[@class=&quot;sc-gsxnyZ KDPRS bigtix-button bigtix-button--primary bigtix-quantity-stepper__stepper bigtix-quantity-stepper__plus&quot;]</value>
      <webElementGuid>42dca494-cada-4dee-86de-0f1fa1085171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>b28f3619-0dc5-41f8-9b59-c4b6d9aba344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='bmspos--layout-scroll-id']/div/main/div/div[2]/ul/div/div[2]/div/div[2]/div/button[2]</value>
      <webElementGuid>ae2a961c-83d1-4469-96e4-38113a6408e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[2]/following::button[2]</value>
      <webElementGuid>1d903f20-85c2-42c6-86ce-710dd49b90c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/following::button[2]</value>
      <webElementGuid>ec14b308-95e8-4052-8bb6-5de64aa615f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Session'])[1]/preceding::button[1]</value>
      <webElementGuid>04d6c275-9193-426f-94b7-dc0ba512eae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon, 04 Dec 2023, 7:39AM'])[1]/preceding::button[1]</value>
      <webElementGuid>9d4f24bf-aaef-4afe-a488-6a322081c2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>67a55a53-5cd2-4182-97d0-1e6ea07f565b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>4d72cf47-a5e6-499b-aa3c-354a050c4902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
