<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08InputText</name>
   <tag></tag>
   <elementGuidId>ddbba810-5d69-4035-9e55-697dc93e3a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-bXDlPE.jmnTlj.bigtix-input-number.bigtix-input-basic.focus-visible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b429b7c-0746-4ede-a68d-116d1ce6c71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bXDlPE jmnTlj bigtix-input-number bigtix-input-basic focus-visible</value>
      <webElementGuid>9518b0dd-a72d-426d-8c92-fe8963bd89a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c345d692-20d8-4fa5-aa12-6751f0813c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>4fd6b239-16db-4074-b3d4-7471175dac15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a172de4c-bca3-4225-8c53-c1c869cdbc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>776</value>
      <webElementGuid>6f020db3-3e46-49c6-9ee4-39ab8ec3084e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>53accb69-6fd8-4b91-b52c-a2a2e002463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d26f347-04c1-45c8-9d5f-5e3bb3beca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bmspos--layout-scroll-id&quot;)/div[@class=&quot;sc-fFubgz cSXbnk&quot;]/main[@class=&quot;ant-layout-content sc-bkzZxe fRXSVe&quot;]/div[@class=&quot;sc-eYErCu gKdRlB bmspos-panel-wrapper&quot;]/div[@class=&quot;sc-bHXZN fPVBKk&quot;]/ul[@class=&quot;sc-iOTrKq iCLerG&quot;]/div[@class=&quot;sc-fEcgnn gnGiqn&quot;]/div[@class=&quot;sc-mlOqW flXQvI&quot;]/div[@class=&quot;sc-ctaXAZ jddcAm bmspos-qty-selection-wrapper&quot;]/div[@class=&quot;bmspos-qty-stepper-wrapper&quot;]/div[@class=&quot;sc-eGCarw kmThIt bigtix-quantity-stepper&quot;]/div[@class=&quot;bigtix-quantity-stepper__quantity&quot;]/input[@class=&quot;sc-bXDlPE jmnTlj bigtix-input-number bigtix-input-basic focus-visible&quot;]</value>
      <webElementGuid>40dc912a-65ad-4e61-af8c-d0eae39d2901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='0']</value>
      <webElementGuid>d9297d42-d0ea-4584-a213-513904eedd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='bmspos--layout-scroll-id']/div/main/div/div[2]/ul/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>323584dc-c253-4134-86fd-6dbed197de40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c7e090be-04e7-4a03-aa5c-f2d5058ee860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>638bc970-50d0-4ce1-9751-f5a96e33dc01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
