<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09ConfirmQuantity</name>
   <tag></tag>
   <elementGuidId>ea000f3b-a0cd-445b-846f-1fdfdb6bffa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-primary.ant-btn-block.sc-gHftXq.fIFJIG.bmspos-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1ca21cc-9e23-47d1-afb3-51919f379dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typo</name>
      <type>Main</type>
      <value>ButtonS</value>
      <webElementGuid>fdac5bb8-e685-406b-a2b7-b421e446c8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdcc59e9-390e-4c71-b2bf-fb723bc208a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button</value>
      <webElementGuid>40b16eee-a124-45e0-ba46-483d09c84a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONFIRM QUANTITY</value>
      <webElementGuid>1f69f0bb-cf22-46d6-b94c-b6e648f8d3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bmspos--layout-scroll-id&quot;)/div[@class=&quot;sc-fFubgz cSXbnk&quot;]/aside[@class=&quot;ant-layout-sider ant-layout-sider-dark sc-kstrdz JCRiS&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/div[@class=&quot;sc-cBNfnY ljIXsm&quot;]/div[@class=&quot;sc-citwmv kODJIQ bmspos-progress-timeline&quot;]/div[@class=&quot;sc-iBaPrD kgzbzw&quot;]/div[@class=&quot;sc-ljwYwh TvPmz&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button&quot;]</value>
      <webElementGuid>149622dd-e7fa-4477-9cb8-45d4a587419e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>cb761773-c717-4594-9047-00d17f5f1e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='bmspos--layout-scroll-id']/div/aside/div/div/div/div[2]/div/button[2]</value>
      <webElementGuid>b74dd339-1ccb-4ae4-ad57-c956578486fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREATE HOLD'])[1]/following::button[1]</value>
      <webElementGuid>5ae17988-030b-46db-a2d9-f24638476781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery &amp; Tickets'])[1]/following::button[2]</value>
      <webElementGuid>5807d3ad-dbad-4760-aeb0-c44f3759293b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>9a548c95-56d6-4d69-8715-d1b07fe930bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/div[2]/div/button[2]</value>
      <webElementGuid>aa72f203-0ba1-4c21-9142-53786fd41c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'CONFIRM QUANTITY' or . = 'CONFIRM QUANTITY')]</value>
      <webElementGuid>4530006b-71e9-4b33-b049-61992edd7981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
