<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10AddToCart</name>
   <tag></tag>
   <elementGuidId>204b501f-5b2d-4fc3-9720-04e7c6d23c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-primary.ant-btn-block.sc-gHftXq.fIFJIG.bmspos-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'ADD TO CART' or . = 'ADD TO CART')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a6b4ade-9fe6-4549-bd7a-39fe784b3888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typo</name>
      <type>Main</type>
      <value>ButtonS</value>
      <webElementGuid>fc665798-5f68-4004-8144-f2c9c5e2b7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23df17af-df9a-431e-90d9-a23351a34f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button</value>
      <webElementGuid>d1033792-0c94-4e8f-9466-f7d950ed4f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD TO CART</value>
      <webElementGuid>e8c78695-9e20-40c1-a6f9-cb9f06f49da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bmspos--layout-scroll-id&quot;)/div[@class=&quot;sc-fFubgz cSXbnk&quot;]/aside[@class=&quot;ant-layout-sider ant-layout-sider-dark sc-kstrdz JCRiS&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/div[@class=&quot;sc-cBNfnY ljIXsm&quot;]/div[@class=&quot;sc-citwmv kODJIQ bmspos-progress-timeline&quot;]/div[@class=&quot;sc-iBaPrD kgzbzw&quot;]/div[@class=&quot;sc-ljwYwh TvPmz&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button&quot;]</value>
      <webElementGuid>ee84891b-f236-401d-9e1a-26d6f738249f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>6cef382e-2842-42a3-a5c6-b12ff55dd742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='bmspos--layout-scroll-id']/div/aside/div/div/div/div[2]/div/button</value>
      <webElementGuid>1cb502e1-1b7d-4ae1-a20a-33b01ff138ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto T1'])[2]/following::button[1]</value>
      <webElementGuid>f964956d-18ad-451e-979f-7efd4665f2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>dd813689-679a-4d9d-8421-2be33c63f571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/div[2]/div/button</value>
      <webElementGuid>5998e733-a7ed-4a39-ac12-d8190e0b3523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ADD TO CART' or . = 'ADD TO CART')]</value>
      <webElementGuid>6174bb72-6cc3-4d66-9312-67998af5dd39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
