<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11CHECKOUT</name>
   <tag></tag>
   <elementGuidId>781a1085-077e-4717-babb-d4aed4416cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'CHECKOUT' or . = 'CHECKOUT')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[1128]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-primary.ant-btn-block.sc-gHftXq.fIFJIG.bmspos-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0114ccb5-b5f5-486d-b3e1-b2b4003f72a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typo</name>
      <type>Main</type>
      <value>ButtonS</value>
      <webElementGuid>3c8914d2-3a14-49de-849a-f1444171140a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64aec3f3-4140-42d7-a656-0ebc67ab123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button</value>
      <webElementGuid>e042804c-2e18-4ddc-b62f-18088b21c643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT</value>
      <webElementGuid>05167595-2bcc-49e1-b396-31b38e66a168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout&quot;]/section[@class=&quot;ant-layout sc-fubCfw jwTLJn&quot;]/main[@class=&quot;ant-layout-content sc-pFZIQ gbgfMs&quot;]/div[@class=&quot;sc-gKsewC jyCpSH&quot;]/div[@class=&quot;sc-ezront CiMZR bmspos-order-cart&quot;]/div[@class=&quot;sc-dYzljZ ghXKxo&quot;]/div[@class=&quot;bmspos-cart-actions&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-block sc-gHftXq fIFJIG bmspos-button&quot;]</value>
      <webElementGuid>dfe1bc82-ba6b-4cb5-b5c2-908ba7d96a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[1128]</value>
      <webElementGuid>65d8d1e6-0393-4dc7-a76c-7c0e712bf781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div[3]/div[3]/div[3]/button</value>
      <webElementGuid>eef187d6-9a28-44fd-9fab-9d3e754baa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S$4.98'])[1]/following::button[1]</value>
      <webElementGuid>cf55b4bd-b212-4163-a23c-b0dbf727ffae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax Inclusive'])[1]/following::button[1]</value>
      <webElementGuid>eae74271-dcc1-4900-b310-aacb1f19dfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>7b9c9742-ff71-4684-80ed-2817e38ad96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>df2a5ae5-a0de-479c-ab03-b9f55a47f1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'CHECKOUT' or . = 'CHECKOUT')]</value>
      <webElementGuid>6f83c706-2db5-4b50-94ef-240831a78a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
