<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05button_839 AM</name>
   <tag></tag>
   <elementGuidId>796a0cb8-aa83-4553-8dac-0734893d1612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bigtix-sessions-list-v2-session-3LZ5-2023-10-20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigtix-sessions-list-v2-session-3LZ5-2023-10-20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbe66e58-b7ae-45f5-8378-13a8f60827b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87d328f5-dbad-492a-bda4-5d82b8838e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-AxgMl hagKUf bigtix-button bigtix-button--ghost sc-pIJJz fTQQXM bigtix-session bigtix-session--oddcell bigtix-session--available bigtix-session--single-date</value>
      <webElementGuid>c1624932-5c9e-4a14-a8eb-1bca1589deb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-session</name>
      <type>Main</type>
      <value>3LZ5</value>
      <webElementGuid>46d682ff-381a-40f6-8d6b-0848c96bff33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>bigtix-test-calendar-session</value>
      <webElementGuid>d3bfc95f-9064-4c8e-873c-6fae4c0fbdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigtix-sessions-list-v2-session-3LZ5-2023-10-20</value>
      <webElementGuid>a7b57be6-1ecf-43f7-b3d3-66c391c9c8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8:39 AM</value>
      <webElementGuid>d90f2786-5ccb-45ae-9fa8-f0439b358388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-sessions-list-v2-session-3LZ5-2023-10-20&quot;)</value>
      <webElementGuid>28ef4a3d-6dd4-432c-b041-a542ba9522e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bigtix-sessions-list-v2-session-3LZ5-2023-10-20']</value>
      <webElementGuid>5f52f37a-1beb-46d5-9271-d6ac70d1ddb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-sessions-list-v2-day-2023-10-20']/div[2]/button</value>
      <webElementGuid>901658e8-c43b-44c5-a6c3-0cdcc679978a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/following::button[1]</value>
      <webElementGuid>812b0eac-281d-49ac-8399-36d3e0998970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November 2023'])[1]/following::button[1]</value>
      <webElementGuid>1f8c0048-8c71-42ca-ba3d-a8a820503a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December 2023'])[1]/preceding::button[1]</value>
      <webElementGuid>78580399-a344-4f0f-9d8b-13412fa733b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[2]/preceding::button[1]</value>
      <webElementGuid>271a66f5-7f27-4e45-aac2-036e508b1c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>33c9ad6f-1a0c-4e5b-b196-200fec08e909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'bigtix-sessions-list-v2-session-3LZ5-2023-10-20' and (text() = '8:39 AM' or . = '8:39 AM')]</value>
      <webElementGuid>e64ce72c-f20f-44ef-889f-9457afc2b252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
