<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06Input_Quantity_Dummy</name>
   <tag></tag>
   <elementGuidId>8caacf97-50ea-4348-b4b7-e1863f706137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sc-fzolEj.ljDdNy.bigtix-input-number.bigtix-input-basic.focus-visible</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>171fe517-1626-4c60-9f1e-592c16a5d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fzolEj ljDdNy bigtix-input-number bigtix-input-basic</value>
      <webElementGuid>ed102da4-ab59-4966-b685-c01b280ec657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5265109-f169-4a4d-bf06-e551b1e3e285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>60aacd25-c091-4301-a4f1-8040009bff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6bafd5e2-77e5-40d8-a5b9-26658f6d7fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>Infinity</value>
      <webElementGuid>f6833457-e210-4547-ab94-adf55219cce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>278d57db-315c-48a0-9a9d-4f59d47d6ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e10db4c7-8bfd-4b6f-bd98-f6501ccb1ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-layout-scroll-id&quot;)/div[@class=&quot;bigtix-booking-layout-body-content-container&quot;]/div[@class=&quot;bigtix-booking-layout-body-content-main bigtix-booking-layout-body-fullheight&quot;]/div[@class=&quot;TicketTypes__Container-xe0o5b-0 kmMoyi TicketXDelivery__StyledTicketTypesWrapper-sc-1sankiu-3 hBuZcv&quot;]/div[@class=&quot;sc-pZBmh dPWHpf bigtix-card Card__StyledTicketTypeCardV2-sc-1765t98-0 cAJkDn bigtix-booking-tickettype-card&quot;]/div[@class=&quot;bigtix-card__content&quot;]/div[@class=&quot;bigtix-card__body&quot;]/div[@class=&quot;bigtix-card__extra&quot;]/div[@class=&quot;sc-paXsP kayDiQ bigtix-quantity-stepper&quot;]/div[@class=&quot;bigtix-quantity-stepper__quantity&quot;]/input[@class=&quot;sc-fzolEj ljDdNy bigtix-input-number bigtix-input-basic focus-visible&quot;]</value>
      <webElementGuid>ce1515c4-0525-4410-91a5-bd7adc560ba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
      <webElementGuid>94e2da94-158a-4b61-9a7d-96a7d452541e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-layout-scroll-id']/div/div[2]/div[5]/div/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>20887209-0cd1-48e8-baa0-2a5d5692c90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>76310632-237e-42ec-aa04-06ff5ec869fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>24c0fe6d-69ad-46b8-ab9b-a6cc2595f985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
