<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09button_Confirm</name>
   <tag></tag>
   <elementGuidId>d3cc78c2-5c05-44b2-b66c-ff294a41e749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bigtix-booking-next-page']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigtix-booking-next-page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e191ae45-842c-4317-9db8-d992fadb9465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c180622-54b1-4af6-9dc2-9ec1d85aa804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-AxgMl MQvkl bigtix-button bigtix-button--primary bigtix-booking-pagenav-next</value>
      <webElementGuid>07abe8db-7973-470c-8c69-3847a4835f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigtix-booking-next-page</value>
      <webElementGuid>0ae3735e-78fd-4717-a2b6-8280829cc320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>test-bigtix-booking--pagenav-next</value>
      <webElementGuid>35726f6b-9f25-4704-9f25-29db4b8cb875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>d2a95814-f94f-4f7c-862d-af7ecafe01de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigtix-booking-next-page&quot;)</value>
      <webElementGuid>7316e9c4-ac30-4ba8-8b47-702f0364996d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bigtix-booking-next-page']</value>
      <webElementGuid>fe7112e1-50b9-48bb-8291-4e15f0c4ad90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigtix-booking-affixed-container']/div/div/div/button</value>
      <webElementGuid>879eafdf-5018-4eb4-9241-c03750dd8857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S$10.00'])[1]/following::button[3]</value>
      <webElementGuid>9291f33e-c9ae-405d-80d0-80e2aca9baeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Type is Created'])[1]/following::button[3]</value>
      <webElementGuid>96eabdbd-18cb-4083-9b6d-17c31c7f80dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'bigtix-booking-next-page', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>79667001-5ddb-4074-b609-d225e57705c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>7cf559ac-5377-4cc6-961c-77f17c733e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'bigtix-booking-next-page' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>42c2995c-fabf-4926-ba53-a753ed47873a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
