#!/usr/bin/env python3
"""Synchronise the shared Katalon core library into every project.

Katalon projects cannot reference source folders outside their own directory, so the shared
framework code in `shared/katalon-core` is copied into each project's `Keywords/` and
`Test Listeners/` folders. The copies carry a header pointing back to the source of truth.

    python tools/sync_core.py           # copy / update files
    python tools/sync_core.py --check   # CI mode: fail if any copy is out of date
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED = REPO_ROOT / "shared" / "katalon-core"
HEADER = "// GENERATED from shared/katalon-core - edit the original and run: python tools/sync_core.py\n"

# module -> files (relative to SHARED) and where they go inside a project
MODULES = {
    "core": ("com/qa/core", "Keywords/com/qa/core", False),
    "web": ("com/qa/core/web", "Keywords/com/qa/core/web", False),
    "mobile": ("com/qa/core/mobile", "Keywords/com/qa/core/mobile", False),
}
LISTENERS = {
    "web": "WebTestListener.groovy",
    "api": "ApiTestListener.groovy",
    "mobile": "MobileTestListener.groovy",
}

# Katalon project type (<type> in the .prj file) -> core flavour
KIND_BY_TYPE = {"WEBUI": "web", "WEBSERVICE": "api", "MOBILE": "mobile"}
IGNORED_DIRS = {".git", "bin", "Libs", "Reports", ".gradle", "build"}


def discover_projects() -> dict[Path, str]:
    """Every folder with a .prj file, mapped to the core flavour it needs."""
    projects = {}
    for prj in sorted(REPO_ROOT.rglob("*.prj")):
        if IGNORED_DIRS & set(prj.relative_to(REPO_ROOT).parts):
            continue
        match = re.search(r"<type>\s*(\w+)\s*</type>", prj.read_text(encoding="utf-8", errors="replace"))
        kind = KIND_BY_TYPE.get(match.group(1) if match else "", "web")
        projects[prj.parent.relative_to(REPO_ROOT)] = kind
    return projects


def expected_files(kind: str) -> dict[Path, str]:
    modules = ["core"] + ([kind] if kind in ("web", "mobile") else [])
    files: dict[Path, str] = {}
    for module in modules:
        source_dir, target_dir, _ = MODULES[module]
        for src in sorted((SHARED / source_dir).glob("*.groovy")):
            files[Path(target_dir) / src.name] = HEADER + src.read_text(encoding="utf-8")
    listener = SHARED / "listeners" / LISTENERS[kind]
    files[Path("Test Listeners") / listener.name] = HEADER + listener.read_text(encoding="utf-8")
    return files


def managed_files(project: Path) -> set[Path]:
    """Files previously generated by this script (identified by the header)."""
    found = set()
    for folder in (project / "Keywords" / "com" / "qa" / "core", project / "Test Listeners"):
        if folder.is_dir():
            for f in folder.rglob("*.groovy"):
                if f.read_text(encoding="utf-8").startswith(HEADER):
                    found.add(f.relative_to(project))
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only report drift, do not write")
    args = parser.parse_args()

    drift = 0
    for rel_project, kind in discover_projects().items():
        project = REPO_ROOT / rel_project
        rel_project = rel_project.as_posix()
        expected = expected_files(kind)
        for rel, content in expected.items():
            target = project / rel
            current = target.read_text(encoding="utf-8") if target.is_file() else None
            if current == content:
                continue
            drift += 1
            if args.check:
                print(f"::error file={(Path(rel_project) / rel).as_posix()}::out of sync with shared/katalon-core")
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8", newline="\n")
                print(f"synced  {rel_project}/{rel.as_posix()}")
        for stale in managed_files(project) - set(expected):
            drift += 1
            if args.check:
                print(f"::error file={(Path(rel_project) / stale).as_posix()}::stale generated file")
            else:
                (project / stale).unlink()
                print(f"removed {rel_project}/{stale.as_posix()}")

    if args.check:
        print("Shared core is in sync." if drift == 0 else f"{drift} file(s) out of sync - run tools/sync_core.py")
        return 1 if drift else 0
    print(f"Done, {drift} file(s) updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
